"""empty message

Revision ID: 0d9e9ead07a3
Revises: aed594017484
Create Date: 2026-04-07 19:25:15.204807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9e9ead07a3'
down_revision: Union[str, Sequence[str], None] = 'aed594017484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversation_states_id'), 'conversation_states', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_states_id'), table_name='conversation_states')
    # ### end Alembic commands ###
