"""add_message_log_and_update_models

Revision ID: 3bb1bb498fd8
Revises: 0d9e9ead07a3
Create Date: 2026-04-09 14:54:13.592564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb1bb498fd8'
down_revision: Union[str, Sequence[str], None] = '0d9e9ead07a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
