"""empty message

Revision ID: aed594017484
Revises: 
Create Date: 2026-04-07 17:26:13.124223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aed594017484'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('phone_country_code', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('profession', sa.Enum('PLUMBER', 'ELECTRICIAN', 'CARPENTER', 'ROOFER', 'PAVER', 'CONCRETE', 'TILER', 'BRICKLAYER', 'PLASTERER', 'GLAZIER', 'INSULATION', 'SCAFFOLDER', 'DEMOLITION', 'GENERAL_CONTRACTOR', 'HVAC', 'BOILER_ENGINEER', 'REFRIGERATION', 'FIRE_PROTECTION', 'PAINTER', 'LANDSCAPER', 'CLEANER', 'HANDYMAN', 'LOCKSMITH', 'POOL_SERVICE', 'PEST_CONTROL', 'WINDOW_CLEANING', 'GUTTER_CLEANING', 'PRESSURE_WASHING', 'TREE_SERVICE', 'FENCING', 'GARAGE_DOOR', 'FLOORING', 'APPLIANCE_REPAIR', 'FURNITURE_REPAIR', 'INTERIOR_DESIGNER', 'VEHICLE_REPAIR', 'VEHICLE_PAINTING', 'VEHICLE_WASHING', 'VEHICLE_TOWING', 'AUTO_ELECTRICIAN', 'MOT_TESTER', 'WELDER', 'BLACKSMITH', 'SHEET_METAL', 'DOCTOR', 'DENTIST', 'PHYSIOTHERAPIST', 'CHIROPRACTOR', 'OPTICIAN', 'PERSONAL_TRAINER', 'MASSAGE_THERAPIST', 'NUTRITIONIST', 'LAWYER', 'ACCOUNTANT', 'FINANCIAL_ADVISOR', 'TAX_CONSULTANT', 'BOOKKEEPER', 'REAL_ESTATE_AGENT', 'PET_SITTER', 'PET_GROOMER', 'VETERINARIAN', 'DOG_TRAINER', 'SOFTWARE_DEVELOPER', 'WEB_DEVELOPER', 'MOBILE_DEVELOPER', 'IT_SUPPORT', 'NETWORK_ENGINEER', 'DATA_ANALYST', 'DATA_SCIENTIST', 'MACHINE_LEARNING_ENGINEER', 'CYBERSECURITY', 'WEB_DESIGNER', 'GRAPHIC_DESIGNER', 'UI_UX_DESIGNER', 'PHOTOGRAPHER', 'VIDEOGRAPHER', 'SEO_SPECIALIST', 'MARKETING_CONSULTANT', 'BUSINESS_CONSULTANT', 'COPYWRITER', 'SOCIAL_MEDIA_MANAGER', 'CATERER', 'EVENT_PLANNER', 'DJ', 'FLORIST', 'TUTOR', 'DRIVING_INSTRUCTOR', 'MUSIC_TEACHER', 'OTHER', name='profession'), nullable=False),
    sa.Column('logo', sa.LargeBinary(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('tax_rate_percent', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('date_format', sa.String(), nullable=False),
    sa.Column('text_direction', sa.String(), nullable=False),
    sa.Column('default_invoice_template_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    # NOTE: FK to document_templates omitted here — added below via ALTER TABLE
    # to break the circular dependency (business_profiles <-> document_templates).
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_email'), 'business_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_business_profiles_id'), 'business_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_business_profiles_phone'), 'business_profiles', ['phone'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('phone_country_code', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OWNER', 'EMPLOYEE', 'INDEPENDENT', name='userrole'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('document_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('html', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('system_prompt_override', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_id'), 'document_templates', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('phone_country_code', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('conversation_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('active_intent', sa.String(), nullable=False),
    sa.Column('pending_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), server_default=sa.text('now() + make_interval(secs=>86400.0)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('QUOTE', 'INVOICE', 'PAID', 'CANCELLED', 'DRAFT', 'VOIDED', name='jobstatus'), nullable=False),
    sa.Column('raw_data', sa.String(), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_invoice_number'), 'jobs', ['invoice_number'], unique=True)
    op.create_table('job_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATED', 'ERROR', name='jobdocumentstatus'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('document_template_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_template_id'], ['document_templates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_documents_id'), 'job_documents', ['id'], unique=False)
    op.create_table('job_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_items_id'), 'job_items', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # Break circular FK: add business_profiles -> document_templates constraint
    # AFTER both tables exist (use_alter=True pattern)
    op.create_foreign_key(
        'fk_business_profiles_default_invoice_template_id',
        'business_profiles', 'document_templates',
        ['default_invoice_template_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_business_profiles_default_invoice_template_id', 'business_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_job_items_id'), table_name='job_items')
    op.drop_table('job_items')
    op.drop_index(op.f('ix_job_documents_id'), table_name='job_documents')
    op.drop_table('job_documents')
    op.drop_index(op.f('ix_jobs_invoice_number'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('conversation_states')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_document_templates_id'), table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_business_profiles_phone'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_id'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_email'), table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
